-- PostgreSQL
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    blocked BOOLEAN NOT NULL,
    login VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(80) NOT NULL,
    password_digest VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);